[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
sleepApplication = false
startCommand = "python -m uvicorn src.palmer_ai.server:app --host 0.0.0.0 --port $8000"
